### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by michaeltansy** [DynamicCodeNinja/RBAC#21]
Hi does this package support l5.2 version?

**Comment by mgolshan** [comment]
I tried it.
It's not compatible with 5.2

**Comment by notf0und** [comment]
I've made a pull request thats fix this package for Laravel 5.3. I thought that its compatible with L5.2 too.
https://github.com/DynamicCodeNinja/RBAC/pull/22

**Comment by sniper7kills** [comment]
I have merged pull request #22.
