### ISSUE TITLE
Method `is` conflict with eloquent model on `HasRoleAndPermission` trait

### ISSUE THREAD

**Issue by veelasky** [DynamicCodeNinja/RBAC#28]
Got this error
`Declaration of DCN\RBAC\Traits\HasRoleAndPermission::is($role, $all = false) should be compatible with Illuminate\Database\Eloquent\Model::is(Illuminate\Database\Eloquent\Model $model)`

Laravel version 5.3.26

conflicting with this [line](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L3101)

**Comment by august** [comment]
Having the same issue. Is this project being maintained any longer?

**Comment by veelasky** [comment]
@august actually if you're using `dev-master` version it is already fixed.

but I really recommend to release a new version to accommodate this changes, since its breaking, preferably with `2.0` maybe.

**Comment by mbm-rafal** [comment]
Guys We're currently starting to extend this package with RBAC lvl 3 and 4.
We want to apply some additional featured as Policies management.

Feel free to join us on https://github.com/mbm-rafal/RBAC

**Comment by sniper7kills** [comment]
@veelasky Thanks for the suggestion!
